spring.application.name=management-service
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/security_library
spring.datasource.username=admin
spring.datasource.password=123456
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=redis123
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8000/realms/security-lib-realm