spring.application.name=user-service
server.port=8081
#sharedlib config
# Th�ng tin secureService
app.security.service.name=user-service
app.security.service.base-url=http://user-service:8081
app.security.service.description=Qu?n l� account ng??i d�ng
# File l?u UUID (t??ng ??i v?i working directory)
app.security.identity-file=config/user-service-security.json
# Kafka topic ?? g?i registration
app.security.registration.topic=security.endpoint.registration
app.security.kafka.bootstrap-servers=localhost:9094
# B?t/t?t (m?c ??nh: true)
app.security.enabled=true
app.security.redis.host=localhost
app.security.redis.port=6379
app.security.redis.password=redis123
app.security.settings.sync.enabled=true

