package vdt.mini.management_service.util.enums;

public enum AnomalyType {
    LATENCY_OUTLIER,
    REQUEST_SIZE_OUTLIER,
    RESPONSE_SIZE_OUTLIER,
    MESSAGE_SIZE_OUTLIER,
    RETRY_OUTLIER,
    NEW_OR_RARE_CLIENT,
    NEW_OR_RARE_SOURCE_IP,
    RARE_ERROR_CODE,
    FAILURE_SPIKE,
    DENIED_SPIKE,
    RETRY_SPIKE,
    TRAFFIC_SPIKE,
    TRAFFIC_DROP,
    LATENCY_DRIFT,
    REQUEST_SIZE_DRIFT,
    RESPONSE_SIZE_DRIFT,
    MESSAGE_SIZE_DRIFT,
    SOURCE_IP_SPIKE,
    CLIENT_DIVERSITY_SPIKE,
    ERROR_DISTRIBUTION_DRIFT,
    UPSTREAM_DEGRADATION,
    DEPENDENCY_INSTABILITY,
    AUTHENTICATION_ATTACK_PATTERN
}
